// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import { DecoManifest } from "$live/types.ts";
import * as $0 from "./functions/LoadGitHubRaw.ts";
import * as $$$$0 from "./routes/404.tsx";
import * as $$$$1 from "./routes/proxy.ts";
import * as $$$$2 from "./routes/api/[...catchall].tsx";
import * as $$$$3 from "./routes/_500.tsx";
import * as $$$$4 from "./routes/_404.tsx";
import * as $$$$5 from "./routes/_app.tsx";
import * as $$$$$0 from "./islands/ui/Navbar.tsx";
import * as $$$$$1 from "./islands/ui/Link.tsx";
import * as $$$$$2 from "./islands/ui/ScrollTop.tsx";
import * as $$$$$3 from "./islands/ui/LinkTo.tsx";
import * as $$$$$4 from "./islands/ui/ScrollBottom.tsx";
import * as $$$$$$$$0 from "./sections/Hero.tsx";
import * as $$$$$$$$1 from "./sections/Navbar.tsx";
import * as $$$$$$$$2 from "./sections/HighlightsWithIcons.tsx";
import * as $$$$$$$$3 from "./sections/HighlightsWithNumbers.tsx";
import * as $$$$$$$$4 from "./sections/Footer.tsx";
import * as $$$$$$$$5 from "./sections/Testimonial2.tsx";
import * as $$$$$$$$6 from "./sections/Head.tsx";
import * as $$$$$$$$7 from "./sections/Testimonial3.tsx";
import * as $$$$$$$$8 from "./sections/HeroWithImage.tsx";
import * as $$$$$$$$9 from "./sections/Testimonial1.tsx";
import * as $$$$$$$$10 from "./sections/Challenge.tsx";
import * as $$$$$$$$11 from "./sections/Photo.tsx";
import * as $$$$$$$$12 from "./sections/CTA.tsx";
import * as $$$$$$$$13 from "./sections/ScrollTop.tsx";
import * as $$$$$$$$14 from "./sections/MainTestimonial.tsx";
import * as $$$$$$$$15 from "./sections/Solution.tsx";
import * as $$$$$$$$16 from "./sections/Solution2.tsx";
import * as $$$$$$$$17 from "./sections/Solution3.tsx";
import * as $$$$$$$$18 from "./sections/About.tsx";
import * as $$$$$$$$19 from "./sections/Summary.tsx";
import * as $live_middleware from "$live/routes/_middleware.ts";
import * as $live_workbench from "$live/routes/live/workbench.ts";
import * as $live_invoke from "$live/routes/live/invoke/index.ts";
import * as $live_editorData from "$live/routes/live/editorData.ts";
import * as $live_inspect from "$live/routes/live/inspect.ts";
import * as $live_meta from "$live/routes/live/_meta.ts";
import * as $live_previews from "$live/routes/live/previews/[...block].tsx";
import * as $live_catchall from "$live/routes/[...catchall].tsx";
import * as i2$$$$2 from "$live/handlers/devPage.ts";
import * as i2$$$$3 from "$live/handlers/fresh.ts";
import * as i2$$$$1 from "$live/handlers/router.ts";
import * as i2$$$$0 from "$live/handlers/routesSelection.ts";
import * as i2$$$$$0 from "$live/pages/LivePage.tsx";
import * as i2$$$9 from "$live/sections/PageInclude.tsx";
import * as i2$$$$$$6 from "$live/matchers/MatchAlways.ts";
import * as i2$$$$$$0 from "$live/matchers/MatchDate.ts";
import * as i2$$$$$$5 from "$live/matchers/MatchEnvironment.ts";
import * as i2$$$$$$3 from "$live/matchers/MatchMulti.ts";
import * as i2$$$$$$4 from "$live/matchers/MatchRandom.ts";
import * as i2$$$$$$2 from "$live/matchers/MatchSite.ts";
import * as i2$$$$$$1 from "$live/matchers/MatchUserAgent.ts";
import * as i2$$$$$$$0 from "$live/flags/audience.ts";
import * as i2$$$$$$$1 from "$live/flags/everyone.ts";
import * as i2$0 from "deco-sites/std/functions/vtexConfig.ts";
import * as i2$1 from "deco-sites/std/functions/vtexProductListingPage.ts";
import * as i2$2 from "deco-sites/std/functions/vndaProductList.ts";
import * as i2$3 from "deco-sites/std/functions/vndaProductDetailsPage.ts";
import * as i2$4 from "deco-sites/std/functions/vtexLegacyProductDetailsPage.ts";
import * as i2$5 from "deco-sites/std/functions/vtexSuggestions.ts";
import * as i2$6 from "deco-sites/std/functions/vtexNavbar.ts";
import * as i2$7 from "deco-sites/std/functions/vtexWishlist.ts";
import * as i2$8 from "deco-sites/std/functions/shopifyProductListingPage.ts";
import * as i2$9 from "deco-sites/std/functions/vtexProductList.ts";
import * as i2$10 from "deco-sites/std/functions/occProductDetailsPage.ts";
import * as i2$11 from "deco-sites/std/functions/vndaProductListingPage.ts";
import * as i2$12 from "deco-sites/std/functions/vtexLegacyProductListingPage.ts";
import * as i2$13 from "deco-sites/std/functions/vtexProductDetailsPage.ts";
import * as i2$14 from "deco-sites/std/functions/vtexLegacyProductList.ts";
import * as i2$15 from "deco-sites/std/functions/shopifyProductList.ts";
import * as i2$16 from "deco-sites/std/functions/shopifyProductDetailsPage.ts";
import * as i2$17 from "deco-sites/std/functions/vtexLegacyRelatedProductsLoader.ts";
import * as i2$$0 from "deco-sites/std/accounts/vnda.ts";
import * as i2$$1 from "deco-sites/std/accounts/yourViews.ts";
import * as i2$$2 from "deco-sites/std/accounts/vtex.ts";
import * as i2$$3 from "deco-sites/std/accounts/shopify.ts";
import * as i2$$4 from "deco-sites/std/accounts/occ.ts";
import * as i2$$$0 from "deco-sites/std/sections/configYourViews.global.tsx";
import * as i2$$$1 from "deco-sites/std/sections/SEO.tsx";
import * as i2$$$2 from "deco-sites/std/sections/SEOPLP.tsx";
import * as i2$$$3 from "deco-sites/std/sections/configOCC.global.tsx";
import * as i2$$$4 from "deco-sites/std/sections/Analytics.tsx";
import * as i2$$$5 from "deco-sites/std/sections/configShopify.global.tsx";
import * as i2$$$6 from "deco-sites/std/sections/configVNDA.global.tsx";
import * as i2$$$7 from "deco-sites/std/sections/configVTEX.global.tsx";
import * as i2$$$8 from "deco-sites/std/sections/SEOPDP.tsx";

const manifest = {
  "functions": {
    "deco-sites/portlabs/functions/LoadGitHubRaw.ts": $0,
    "deco-sites/std/functions/occProductDetailsPage.ts": i2$10,
    "deco-sites/std/functions/shopifyProductDetailsPage.ts": i2$16,
    "deco-sites/std/functions/shopifyProductList.ts": i2$15,
    "deco-sites/std/functions/shopifyProductListingPage.ts": i2$8,
    "deco-sites/std/functions/vndaProductDetailsPage.ts": i2$3,
    "deco-sites/std/functions/vndaProductList.ts": i2$2,
    "deco-sites/std/functions/vndaProductListingPage.ts": i2$11,
    "deco-sites/std/functions/vtexConfig.ts": i2$0,
    "deco-sites/std/functions/vtexLegacyProductDetailsPage.ts": i2$4,
    "deco-sites/std/functions/vtexLegacyProductList.ts": i2$14,
    "deco-sites/std/functions/vtexLegacyProductListingPage.ts": i2$12,
    "deco-sites/std/functions/vtexLegacyRelatedProductsLoader.ts": i2$17,
    "deco-sites/std/functions/vtexNavbar.ts": i2$6,
    "deco-sites/std/functions/vtexProductDetailsPage.ts": i2$13,
    "deco-sites/std/functions/vtexProductList.ts": i2$9,
    "deco-sites/std/functions/vtexProductListingPage.ts": i2$1,
    "deco-sites/std/functions/vtexSuggestions.ts": i2$5,
    "deco-sites/std/functions/vtexWishlist.ts": i2$7,
  },
  "routes": {
    "./routes/_404.tsx": $$$$4,
    "./routes/_500.tsx": $$$$3,
    "./routes/_app.tsx": $$$$5,
    "./routes/_middleware.ts": $live_middleware,
    "./routes/[...catchall].tsx": $live_catchall,
    "./routes/404.tsx": $$$$0,
    "./routes/api/[...catchall].tsx": $$$$2,
    "./routes/index.tsx": $live_catchall,
    "./routes/live/_meta.ts": $live_meta,
    "./routes/live/editorData.ts": $live_editorData,
    "./routes/live/inspect.ts": $live_inspect,
    "./routes/live/invoke/index.ts": $live_invoke,
    "./routes/live/previews/[...block].tsx": $live_previews,
    "./routes/live/workbench.ts": $live_workbench,
    "./routes/proxy.ts": $$$$1,
  },
  "islands": {
    "./islands/ui/Link.tsx": $$$$$1,
    "./islands/ui/LinkTo.tsx": $$$$$3,
    "./islands/ui/Navbar.tsx": $$$$$0,
    "./islands/ui/ScrollBottom.tsx": $$$$$4,
    "./islands/ui/ScrollTop.tsx": $$$$$2,
  },
  "sections": {
    "$live/sections/PageInclude.tsx": i2$$$9,
    "deco-sites/portlabs/sections/About.tsx": $$$$$$$$18,
    "deco-sites/portlabs/sections/Challenge.tsx": $$$$$$$$10,
    "deco-sites/portlabs/sections/CTA.tsx": $$$$$$$$12,
    "deco-sites/portlabs/sections/Footer.tsx": $$$$$$$$4,
    "deco-sites/portlabs/sections/Head.tsx": $$$$$$$$6,
    "deco-sites/portlabs/sections/Hero.tsx": $$$$$$$$0,
    "deco-sites/portlabs/sections/HeroWithImage.tsx": $$$$$$$$8,
    "deco-sites/portlabs/sections/HighlightsWithIcons.tsx": $$$$$$$$2,
    "deco-sites/portlabs/sections/HighlightsWithNumbers.tsx": $$$$$$$$3,
    "deco-sites/portlabs/sections/MainTestimonial.tsx": $$$$$$$$14,
    "deco-sites/portlabs/sections/Navbar.tsx": $$$$$$$$1,
    "deco-sites/portlabs/sections/Photo.tsx": $$$$$$$$11,
    "deco-sites/portlabs/sections/ScrollTop.tsx": $$$$$$$$13,
    "deco-sites/portlabs/sections/Solution.tsx": $$$$$$$$15,
    "deco-sites/portlabs/sections/Solution2.tsx": $$$$$$$$16,
    "deco-sites/portlabs/sections/Solution3.tsx": $$$$$$$$17,
    "deco-sites/portlabs/sections/Summary.tsx": $$$$$$$$19,
    "deco-sites/portlabs/sections/Testimonial1.tsx": $$$$$$$$9,
    "deco-sites/portlabs/sections/Testimonial2.tsx": $$$$$$$$5,
    "deco-sites/portlabs/sections/Testimonial3.tsx": $$$$$$$$7,
    "deco-sites/std/sections/Analytics.tsx": i2$$$4,
    "deco-sites/std/sections/configOCC.global.tsx": i2$$$3,
    "deco-sites/std/sections/configShopify.global.tsx": i2$$$5,
    "deco-sites/std/sections/configVNDA.global.tsx": i2$$$6,
    "deco-sites/std/sections/configVTEX.global.tsx": i2$$$7,
    "deco-sites/std/sections/configYourViews.global.tsx": i2$$$0,
    "deco-sites/std/sections/SEO.tsx": i2$$$1,
    "deco-sites/std/sections/SEOPDP.tsx": i2$$$8,
    "deco-sites/std/sections/SEOPLP.tsx": i2$$$2,
  },
  "handlers": {
    "$live/handlers/devPage.ts": i2$$$$2,
    "$live/handlers/fresh.ts": i2$$$$3,
    "$live/handlers/router.ts": i2$$$$1,
    "$live/handlers/routesSelection.ts": i2$$$$0,
  },
  "pages": {
    "$live/pages/LivePage.tsx": i2$$$$$0,
  },
  "matchers": {
    "$live/matchers/MatchAlways.ts": i2$$$$$$6,
    "$live/matchers/MatchDate.ts": i2$$$$$$0,
    "$live/matchers/MatchEnvironment.ts": i2$$$$$$5,
    "$live/matchers/MatchMulti.ts": i2$$$$$$3,
    "$live/matchers/MatchRandom.ts": i2$$$$$$4,
    "$live/matchers/MatchSite.ts": i2$$$$$$2,
    "$live/matchers/MatchUserAgent.ts": i2$$$$$$1,
  },
  "flags": {
    "$live/flags/audience.ts": i2$$$$$$$0,
    "$live/flags/everyone.ts": i2$$$$$$$1,
  },
  "accounts": {
    "deco-sites/std/accounts/occ.ts": i2$$4,
    "deco-sites/std/accounts/shopify.ts": i2$$3,
    "deco-sites/std/accounts/vnda.ts": i2$$0,
    "deco-sites/std/accounts/vtex.ts": i2$$2,
    "deco-sites/std/accounts/yourViews.ts": i2$$1,
  },
  "config": config,
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest satisfies DecoManifest;
